config/routes.rb
Rails.application.routes.draw do
  resources :components, only: [:index, :show] do
    collection do
      Styleus::Component.sections.each do |section, _|
        section_route = section.to_s.pluralize
        resources section_route, only: [:index, :show], controller: :components, components: section_route
      end
    end
  end
end

app/models/styleus/base.rb
module Styleus
  # Provides a basic model, with attribute and
  # naming capabilities.
  # TODO: replace with ActiveModel::Model or something like that
  class Base
    extend ActiveModel::Naming
    include ActiveModel::AttributeMethods
    include ActiveModel::Serialization

    def initialize(attributes)
      @attributes = attributes
    end

    def id
      nil
    end

    # as implemented as in ActiveRecord
    def to_key
      key = self.id
      [key] if key
    end

    private

    def attribute(attr)
      @attributes[attr.to_sym]
    end

    class << self
      def with_attributes(*attribute_names)
        define_attribute_methods attribute_names.map(&:to_s)
      end
    end
  end
end

app/models/styleus/component.rb
module Styleus
  class Component
    class_attribute :_sections, :components, :_section_name

    class << self
      def components(*new_components)
        return registered_components if new_components.empty?

        registered_components.push(*new_components).uniq!
        registered_components
      end

      def registered_components
        styleus_sections[section_key] ||= []
      end

      def styleus_sections
        ::Styleus::Component.sections
      end

      def sections
        self._sections ||= { }
      end

      def section_key
        section_name.to_sym
      end

      def section_name
        self._section_name ||= to_underscore
      end

      def to_underscore
        underscored_module_name
      end

      private

      def underscored_module_name
        underscored_name.gsub('/', '_')
      end

      def underscored_name
        name.underscore
      end
    end
  end
end

app/models/styleus/view_component.rb
module Styleus
  class ViewComponent < Styleus::Base
    with_attributes :headline, :partial_path, :helper

    # id is used as anchor id in the anchor menu,
    # so it has to be a uid.
    # TODO: make sure the uid-ness :)
    def id
      headline.underscore.gsub(/ /, '_')
    end

    def to_s
      headline.humanize.pluralize
    end

    class << self
      def components
        @components ||= []
      end

      def from_hashes(hashes)
        components.clear
        hashes.each { |comp_hash| components << new(comp_hash) }
        components
      end

      def from_names(section, names)
        components.clear
        names.each do |name|
          components << new(
                  headline: name.to_s.humanize,
                  partial_path: File.join('components', section, "#{name}"))
        end
        components
      end
    end
  end
end

app/helpers/styleus_helper.rb
require 'styleus_representer_helper'

module StyleusHelper
  def _section
    params[:components]
  end

  def _application_context(&block)
    captured_block = capture(&block)

    layout_name = 'styleus_context'
    file_name   = "_#{layout_name}.html.erb"

    if _layout_exists?(file_name)
      render(layout: File.join('layouts', layout_name)) { captured_block }
    else
      captured_block
    end
  end

  def _component_context(file_path, &block)
    captured_block = capture(&block)

    view_path = _folder_path(file_path)

    partial_name = 'component_context'
    partial_path = File.join view_path, 'component_context'
    file_path    = File.join view_path, "_#{partial_name}.html.erb"

    if _partial_exists?(file_path)
      render(layout: partial_path) { captured_block }
    else
      captured_block
    end
  end

  def _folder_path(path)
    path = path.split(File::SEPARATOR)
    path.pop
    path.join(File::SEPARATOR)
  end

  def _partial_exists?(view_path)
    file_path = Rails.root.join('app', 'views', view_path)
    File.exists? file_path
  end

  def _layout_exists?(file_name)
    file_path = Rails.root.join('app', 'views', 'layouts', file_name)
    File.exists? file_path
  end

  # this heart of gold function renders the app component partials
  # and enables the configured content_for blocks for the target
  # partial called styleus_partials.
  def _styleus_partials(component, options = { })
    _clear_content_for_registrations(:documentation, :representation, :html, :helper)
    # execute application partial without responding it directly,
    # so only the given content_for methods will help.
    render partial: "#{component.partial_path}", locals: { component: component }

    # returning concatenating responder partial, which consists of content_for blocks only.
    result = render(layout: 'styleus/styleus_partials', locals: { component: component }) { }
    flush_output_buffer
    _clear_content_for_registrations(:documentation, :representation, :html, :helper)
    result
  end

  # clean up content_for blocks, so same content_for names can be used several times
  def _clear_content_for_registrations(*content_names)
    # clear content_for calls for this name
    content_names.each { |content_name| @view_flow.set(content_name, '') }
  end


  # converts the list of component hashes configured in the
  # app to a list of ViewComponent instances.
  def _build_view_components
    @components ||= Styleus::ViewComponent.from_names(_section, _section_class.components)
  end

  def _section_class
    _section.camelcase.singularize.constantize
  end

  # wraps a component in an article and combines it with
  # a depending optionbar, that enables the user to show
  # and hide the different partials.
  def _wrap_component(component)
    _styleus_article_wrap(component) do
      _styleus_partials(component)
    end
  end

  def _option_bar(component)
    _option_bar(component)
  end

  # renders an article attribute wrap for a component
  def _styleus_article_wrap(component, &block)
    captured_block = capture(&block)
    _article(component) { captured_block }
  end

  def _styleus_component_wrap(options = { }, &block)
    captured_block = capture(&block)
    classes        = %W{__sg_component #{options[:class]}}.join(' ')
    _component(classes, options[:partial_path]) { captured_block }
  end

  # TODO: what does this method do?
  def _styleus_documentation_wrap(options = { }, &block)
    captured_block = capture(&block)
  end

  def _html_representation(&block)
    _coderay_highlight_wrap('HTML Snippet', &block)
  end

  def _helper_representation(&block)
    _coderay_highlight_wrap('Rails Helper', type: :ruby, &block)
  end

  def _coderay_highlight_wrap(note = nil, options = { }, &block)
    captured_block = capture(&block)
    type           = options[:type] || :html

    highlighted_code = _highlight(captured_block.to_s, type)
    code_with_note   = _code_note(note).concat highlighted_code

    _code(code_with_note, type)
  end

  def _highlight(code, type)
    CodeRay.scan(code, type).div(:css => :class, line_numbers: :table).html_safe
  end
end

app/views/styleus/_article.html.erb
<article class="__sg_article" id="<%= id %>">
  <header>
    <%= content_tag 'h3', headline if headline %>
  </header>
  <%= yield %>
</article>

app/views/styleus/_code.html.erb
<%= content_tag('div', data: { subject: "#{type}-representation" }) do %>
  <%= code.html_safe %>
<% end %>

app/views/styleus/_code_note.html.erb
<p class="__code_note"><%= code_note %></p>

app/views/styleus/_component.html.erb
<section class="<%= classes %>">
  <%= _application_context do %>
    <%= _component_context(partial_path) do %>
      <%= yield %>
    <% end %>
  <% end %>
</section>

app/views/styleus/_component_index.html.erb
<% unless components.empty? %>
  <nav class="__component_index">
    <%= content_tag 'h3', headline if headline %>
    <ul>
      <%= content_tag_for(:li, components) do |component| %>
        <%= link_to component.to_s, anchor: component.id %>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/styleus/_option_bar.html.erb
<nav class="__option_bar">
  <ul>
    <li><%= link_to t('icons.html'), component_path(component),
                    title: t('links.titles.html'), class: 'icon', data: { toggle: "##{component.id} [data-subject=html-representation]" } %></li>

    <% if helper %>
      <li><%= link_to t('icons.helper'), component_path(component),
                      title: t('links.titles.helper'), class: 'icon', data: { toggle: "##{component.id} [data-subject=ruby-representation]" } %></li>
    <% end %>

    <li><%= link_to t('icons.expand_all'), component_path(component),
                    title: t('links.titles.expand_all'), class: 'icon', data: { toggle: "##{component.id} [data-subject*=representation]" } %></li>
  </ul>
</nav>

app/views/styleus/_screen_size_viewer.html.erb
<section class="__mq_presenter">
<ul class="__mq_screen_size_list">
  <li class="__mq_step one">&lt; 1024px</li>
  <li class="__mq_step two">1024px &lt;&gt; 1480px</li>
  <li class="__mq_step three">&gt; 1480px</li>
</ul>
</section>

app/views/styleus/_styleus_partials.html.erb
<% if content_for? :documentation %>
  <section class="__documentation">
    <%= content_for(:documentation).html_safe %>
  </section>
<% end %>

<section class="__code_partials">
  <%= _option_bar(component, content_for?(:helper)) %>
  <%= _styleus_component_wrap(partial_path: component.partial_path) { content_for(:representation).html_safe } %>
  <%= content_for(:html).html_safe %>
  <%= content_for(:helper).html_safe %>
</section>